
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author mustafasamil.ileri
 */
public class frm_main extends javax.swing.JFrame {

    /**
     * Creates new form frm_main
     */
    public frm_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_person_allData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JFiledState = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_person_surname = new javax.swing.JTextField();
        txt_person_country = new javax.swing.JTextField();
        txt_person_city = new javax.swing.JTextField();
        txt_person_ptzpCode = new javax.swing.JTextField();
        txt_person_state = new javax.swing.JTextField();
        txt_person_address = new javax.swing.JTextField();
        txt_person_name = new javax.swing.JTextField();
        cmbx_categoriy = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        label_errorMsg = new javax.swing.JLabel();
        txt_addNewCategoriy = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_addItem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txt_categoriySize = new javax.swing.JTextField();
        list1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane2.setBackground(new java.awt.Color(0, 204, 204));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane2.setToolTipText(" ");

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setMaximumSize(new java.awt.Dimension(1007, 621));
        jPanel5.setMinimumSize(new java.awt.Dimension(1007, 621));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Surname  : ");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 125, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Categoriy  : ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 128, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Counrty : ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 71, 63, -1));

        tabel_person_allData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Surname", "Counrty", "City", "District/City/State", "Postal/Zip Code", "Address", "Categoriy"
            }
        ));
        tabel_person_allData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_person_allDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabel_person_allDataMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_person_allData);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 931, 287));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("City : ");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 126, 57, -1));

        JFiledState.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        JFiledState.setText("District/County/State :");
        jPanel5.add(JFiledState, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 71, 161, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Postal /Zip Code     :");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 126, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("Address   :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 71, 69, -1));
        jPanel5.add(txt_person_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 123, 120, 29));
        jPanel5.add(txt_person_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 66, 120, 34));
        jPanel5.add(txt_person_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 119, 120, 37));
        jPanel5.add(txt_person_ptzpCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 119, 120, 37));
        jPanel5.add(txt_person_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 66, 120, 34));
        jPanel5.add(txt_person_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 64, 195, 37));
        jPanel5.add(txt_person_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 67, 120, 31));

        cmbx_categoriy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Work", "Gym" }));
        cmbx_categoriy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(cmbx_categoriy, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 119, 195, 37));

        btn_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon("C:\\Users\\mustafasamil.ileri\\Documents\\NetBeansProjects\\AdresTakipSistemi\\icons\\icons8-add-34.png")); // NOI18N
        btn_add.setText("Add ");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel5.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, 39));

        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon("C:\\Users\\mustafasamil.ileri\\Documents\\NetBeansProjects\\AdresTakipSistemi\\icons\\icons8-empty-trash-30.png")); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel5.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, -1, -1));

        btn_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon("C:\\Users\\mustafasamil.ileri\\Documents\\NetBeansProjects\\AdresTakipSistemi\\icons\\icons8-update-30.png")); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel5.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));

        label_errorMsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_errorMsg.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(label_errorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 420, 20));

        txt_addNewCategoriy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addNewCategoriyActionPerformed(evt);
            }
        });
        jPanel5.add(txt_addNewCategoriy, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 200, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("New Categoriy : ");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, 20));

        btn_addItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\mustafasamil.ileri\\Documents\\NetBeansProjects\\AdresTakipSistemi\\icons\\icons8-add-30.png")); // NOI18N
        btn_addItem.setText("New Categoriy");
        btn_addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addItemActionPerformed(evt);
            }
        });
        jPanel5.add(btn_addItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 250, 150, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1120, -1));

        jTabbedPane2.addTab("Person Register Page", jPanel4);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jCheckBox1.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox1.setText("Work");

        jCheckBox2.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox2.setText("Home");

        jCheckBox3.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox3.setText("Gym");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Number of Categoriy");

        txt_categoriySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoriySizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_categoriySize, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(587, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(500, 500, 500))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_categoriySize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Person Check Address", jPanel3);

        getContentPane().add(jTabbedPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        label_errorMsg.setText("");
        DefaultTableModel personData = (DefaultTableModel) tabel_person_allData.getModel();
        if (txt_person_address.getText().trim().equals("")) {
            label_errorMsg.setText(" Adrress can't be empty !!!");

        } else {

            Object[] addes = {txt_person_name.getText(),
                txt_person_surname.getText(),
                txt_person_country.getText(),
                txt_person_city.getText(),
                txt_person_state.getText(),
                txt_person_ptzpCode.getText(),
                txt_person_address.getText(),
                cmbx_categoriy.getSelectedItem().toString()};
            personData.addRow(addes);
        }

        String name = txt_person_name.getText();
        String surname = txt_person_surname.getText();
        String counrty = txt_person_country.getText();
        String city = txt_person_city.getText();
        String state = txt_person_state.getText();
        int ptzpcode = Integer.parseInt(txt_person_ptzpCode.getText());
        String address = txt_person_address.getText();
        String categoriy = cmbx_categoriy.getSelectedItem().toString();

        Person person = new Person(name, surname, counrty, city, state, ptzpcode, address, categoriy);
        
       boolean addPersonYes= DataManage.AddUser(person);
        
        if(addPersonYes){
            JOptionPane.showMessageDialog(rootPane, "add was succeced");
        }else {
            JOptionPane.showMessageDialog(rootPane, "Something was wrong","Add",JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:

        label_errorMsg.setText("");
        
        DefaultTableModel personData = (DefaultTableModel) tabel_person_allData.getModel();
        
        int selectedRow = tabel_person_allData.getSelectedRow();

        if (selectedRow == -1) {
            if (tabel_person_allData.getRowCount() == 0) {
                label_errorMsg.setText("Tabel is Empty !");
            } else {
                label_errorMsg.setText("Please selecet ");
            }
        } else {
            personData.setValueAt(txt_person_name.getText(), selectedRow, 0);
            personData.setValueAt(txt_person_surname.getText(), selectedRow, 1);
            personData.setValueAt(txt_person_country.getText(), selectedRow, 2);
            personData.setValueAt(txt_person_city.getText(), selectedRow, 3);
            personData.setValueAt(txt_person_state.getText(), selectedRow, 4);
            personData.setValueAt(txt_person_ptzpCode.getText(), selectedRow, 5);
            personData.setValueAt(txt_person_address.getText(), selectedRow, 6);
            personData.setValueAt(cmbx_categoriy.getSelectedItem().toString(), selectedRow, 7);

            /*
            String name = txt_person_address.getText();
            String surname = txt_person_surname.getText();
            String counrty = txt_person_country.getText();
            String city = txt_person_city.getText();
            String state = txt_person_state.getText();
            int ptzpcode = Integer.parseInt(txt_person_ptzpCode.getText());
            String address = txt_person_address.getText();
            String categoriy = cmbx_categoriy.getSelectedItem().toString();

            Person person = new Person(name, surname, counrty, city, state, ptzpcode, address, categoriy);
            */
            
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tabel_person_allDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_person_allDataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_person_allDataMouseEntered

    private void tabel_person_allDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_person_allDataMouseClicked
        // TODO add your handling code here:
        
        
        DefaultTableModel personData = (DefaultTableModel) tabel_person_allData.getModel();
        
        int selectedRow = tabel_person_allData.getSelectedRow();
        
                txt_person_name.setText(personData.getValueAt(selectedRow,0).toString());
                txt_person_surname.setText(personData.getValueAt(selectedRow,1).toString());
                txt_person_country.setText(personData.getValueAt(selectedRow,2).toString());
                txt_person_city.setText(personData.getValueAt(selectedRow,3).toString());
                txt_person_state.setText(personData.getValueAt(selectedRow,4).toString());
                txt_person_ptzpCode.setText(personData.getValueAt(selectedRow,5).toString());
                txt_person_address.setText(personData.getValueAt(selectedRow,6).toString());
                cmbx_categoriy.setSelectedItem(personData.getValueAt(selectedRow,7).toString());
        
    }//GEN-LAST:event_tabel_person_allDataMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        label_errorMsg.setText("");
         DefaultTableModel personData = (DefaultTableModel) tabel_person_allData.getModel();
        
        int selectedRow = tabel_person_allData.getSelectedRow();
        
        if(selectedRow==-1){
            if(tabel_person_allData.getRowCount()==0){
                label_errorMsg.setText("Person Data Table is Empty");
       
            }else{
                label_errorMsg.setText("please Selecete one Item");
            }
            
        }else{
            personData.removeRow(selectedRow);
            
            label_errorMsg.setText(" Item was cleared !!! ");
        }
        
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addItemActionPerformed
        // TODO add your handling code here:
       
        String addValue=txt_addNewCategoriy.getText();
        cmbx_categoriy.addItem(addValue);
    }//GEN-LAST:event_btn_addItemActionPerformed

    private void txt_categoriySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoriySizeActionPerformed
        
        
 
       
        
        
    }//GEN-LAST:event_txt_categoriySizeActionPerformed

    private void txt_addNewCategoriyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addNewCategoriyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addNewCategoriyActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frm_main().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JFiledState;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addItem;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmbx_categoriy;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label_errorMsg;
    private java.awt.List list1;
    private javax.swing.JTable tabel_person_allData;
    private javax.swing.JTextField txt_addNewCategoriy;
    private javax.swing.JTextField txt_categoriySize;
    private javax.swing.JTextField txt_person_address;
    private javax.swing.JTextField txt_person_city;
    private javax.swing.JTextField txt_person_country;
    private javax.swing.JTextField txt_person_name;
    private javax.swing.JTextField txt_person_ptzpCode;
    private javax.swing.JTextField txt_person_state;
    private javax.swing.JTextField txt_person_surname;
    // End of variables declaration//GEN-END:variables
}
